### ISSUE TITLE
PATHWAY_COMMONS import fails

### ISSUE THREAD

**Issue by cebel** [e-bel/ebel#13]
ERROR:ebel.manager.orientdb.odb_meta:https://www.pathwaycommons.org/archives/PC2/v13/PathwayCommons13.Detailed.hgnc.txt.gz could not be downloaded!

**Comment by brucetony** [comment]
I could not find v13 in the [FTP server ](https://www.pathwaycommons.org/archives/), I went with the latest version I could find: https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.Detailed.hgnc.txt.gz
