### ISSUE TITLE
KEGG import fails

### ISSUE THREAD

**Issue by cebel** [e-bel/ebel#14]
File "/usr/local/lib/python3.9/site-packages/ebel/manager/orientdb/biodbs/kegg.py", line 267, in update_interactions
    interaction_type, subject_name, object_name, kegg_species_id = key
ValueError: too many values to unpack (expected 4)

**Comment by brucetony** [comment]
The `df.groupby()` method of aggregating properties into a key wasn't working as intended. Implemented a more verbose but functional work around which is working. Added to a TODO for optimizing it later, but not high priority
