### ISSUE TITLE
IUPHAR import fails

### ISSUE THREAD

**Issue by cebel** [e-bel/ebel#15]
File "/usr/local/lib/python3.9/site-packages/ebel/manager/orientdb/biodbs/iuphar.py", line 66, in insert_ligand_data
    df.to_sql(iuphar.IupharLigand.__tablename__, self.engine, if_exists='append')

pymysql.err.DataError: (1366, "Incorrect integer value: 'ENSG00000125657' for column 'ensembl_id' at row 219")

**Comment by brucetony** [comment]
Simple change to string in the models and works now
