### ISSUE TITLE
  Responsible & Private vulnerability disclosure

### ISSUE THREAD

**Issue by Sim4n6** [e-bel/ebel#9]
Hi,

I may have identified a low-severity vulnerability in e-bel/ebel codebase. Please consider enabling the GitHub private vulnerability reporting so the process can go smoothly...

    https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

Thank you in advance

**Comment by brucetony** [comment]
CodeQL has been implemented, thank you for bringing this to our attention

**Comment by Sim4n6** [comment]
I was more expecting that you enable private reporting feature so that I submit a vulnerability report...
